/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

USE `cbb_pf`;/* 外键已删除现在要重新建立*/
ALTER TABLE `t_nj_inventory` 
	DROP FOREIGN KEY `FK_REFERENCE_4`  ;


/* Alter table in target */
ALTER TABLE `t_nj_inventory` 
	ADD COLUMN `MAIN_BILL_NO` varchar(50)  COLLATE utf8_general_ci NULL COMMENT '总运单号' after `NET_WEIGHT` , 
	CHANGE `NOTE` `NOTE` varchar(1000)  COLLATE utf8_general_ci NULL COMMENT '备注' after `MAIN_BILL_NO` , 
	CHANGE `RETURN_STATUS` `RETURN_STATUS` int(11)   NULL COMMENT '回执状态--操作结果（1电子口岸已暂存/2电子口岸申报中/3发送海关成功/4发送海关失败/100海关退单/120海关入库成功/399海关审结）,若小于0数字表示处理异常回执' after `NOTE` , 
	CHANGE `RETURN_TIME` `RETURN_TIME` varchar(64)  COLLATE utf8_general_ci NULL COMMENT '回执时间--操作时间(格式:YYYYMMDDhhmmss)' after `RETURN_STATUS` , 
	CHANGE `RETURN_INFO` `RETURN_INFO` varchar(1000)  COLLATE utf8_general_ci NULL COMMENT '回执信息--备注（如:退单原因）' after `RETURN_TIME` , 
	CHANGE `CREAT_TIME` `CREAT_TIME` datetime   NULL after `RETURN_INFO` , 
	CHANGE `UPDATE_TIME` `UPDATE_TIME` timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP  on update CURRENT_TIMESTAMP after `CREAT_TIME` , 
	CHANGE `VERSION` `VERSION` varchar(16)  COLLATE utf8_general_ci NULL DEFAULT 'V1.0' COMMENT '版本号' after `UPDATE_TIME` ;

/*  Alter View in target  */
DELIMITER $$
DROP VIEW IF EXISTS `v_nj_inventory`$$

CREATE ALGORITHM=UNDEFINED DEFINER=`ftsp`@`localhost` SQL SECURITY DEFINER VIEW `v_nj_inventory` AS select `i`.`INVENTORY_ID` AS `INVENTORY_ID`,`i`.`GUID` AS `GUID`,`i`.`CUSTOM_CODE` AS `CUSTOM_CODE`,`i`.`RECEIVER_ID` AS `RECEIVER_ID`,`i`.`CHK_CUSTOM_CODE` AS `CHK_CUSTOM_CODE`,`i`.`APP_TYPE` AS `APP_TYPE`,`i`.`APP_TIME` AS `APP_TIME`,`i`.`APP_STATUS` AS `APP_STATUS`,`i`.`APP_UID` AS `APP_UID`,`i`.`APP_UNAME` AS `APP_UNAME`,`i`.`COP_NO` AS `COP_NO`,`i`.`PRE_NO` AS `PRE_NO`,`i`.`LOGISTICS_NO` AS `LOGISTICS_NO`,`i`.`INVT_NO` AS `INVT_NO`,`i`.`PORT_CODE` AS `PORT_CODE`,`i`.`IE_DATE` AS `IE_DATE`,`i`.`OWNER_CODE` AS `OWNER_CODE`,`i`.`OWNER_NAME` AS `OWNER_NAME`,`i`.`TRADE_MODE` AS `TRADE_MODE`,`i`.`LOCT_NO` AS `LOCT_NO`,`i`.`LICENSE_NO` AS `LICENSE_NO`,`i`.`COUNTRY` AS `COUNTRY`,`i`.`GOODS_VALUE` AS `GOODS_VALUE`,`i`.`GOODS_CURRENCY` AS `GOODS_CURRENCY`,`i`.`TAX_FEE` AS `TAX_FEE`,`i`.`DESTINATION_PORT` AS `DESTINATION_PORT`,`i`.`FREIGHT` AS `FREIGHT`,`i`.`FREIGHT_CURR` AS `FREIGHT_CURR`,`i`.`FREIGHT_MARK` AS `FREIGHT_MARK`,`i`.`INSURE_FEE` AS `INSURE_FEE`,`i`.`INSURE_FEE_CURR` AS `INSURE_FEE_CURR`,`i`.`INSURE_FEE_MARK` AS `INSURE_FEE_MARK`,`i`.`WRAP_TYPE` AS `WRAP_TYPE`,`i`.`PACK_NO` AS `PACK_NO`,`i`.`WEIGHT` AS `WEIGHT`,`i`.`NET_WEIGHT` AS `NET_WEIGHT`,`i`.`MAIN_BILL_NO` AS `MAIN_BILL_NO`,`i`.`NOTE` AS `NOTE`,`i`.`RETURN_STATUS` AS `RETURN_STATUS`,`i`.`RETURN_TIME` AS `RETURN_TIME`,`i`.`RETURN_INFO` AS `RETURN_INFO`,`i`.`CREAT_TIME` AS `CREAT_TIME`,`i`.`UPDATE_TIME` AS `UPDATE_TIME`,`i`.`VERSION` AS `VERSION`,`l`.`LOGISTICS_CODE` AS `LOGISTICS_CODE`,`l`.`IE_FLAG` AS `IE_FLAG`,`l`.`TRAF_MODE` AS `TRAF_MODE`,`l`.`VOYAGE_NO` AS `VOYAGE_NO`,`l`.`BILL_NO` AS `BILL_NO`,`l`.`TRAF_NAME` AS `TRAF_NAME`,`o`.`ORDER_NO` AS `ORDER_NO`,`o`.`EBP_CODE` AS `EBP_CODE`,`o`.`EBC_CODE` AS `EBC_CODE`,`o`.`AGENT_CODE` AS `AGENT_CODE` from ((`t_nj_inventory` `i` left join `t_nj_logistics` `l` on((`l`.`LOGISTICS_NO` = `i`.`LOGISTICS_NO`))) left join `t_nj_orders` `o` on((`l`.`ORDER_NO` = `o`.`ORDER_NO`)))$$
DELIMITER ;
/* 外键已删除现在要重新建立*/
ALTER TABLE `t_nj_inventory` 
	ADD CONSTRAINT `FK_REFERENCE_4` 
	FOREIGN KEY (`LOGISTICS_NO`) REFERENCES `t_nj_logistics` (`LOGISTICS_NO`) ;

/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;